# Generated by Django 4.0.3 on 2022-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.URLField(default='default'),
            preserve_default=False,
        ),
    ]
