# Generated by Django 4.0.3 on 2022-05-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_channel_recommended_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_channel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.channel'),
            preserve_default=False,
        ),
    ]
